### ISSUE TITLE
saveSvg: ascii codec can't encode character

### ISSUE THREAD

**Issue by chrimbo** [cduck/drawSvg#43] opened 2021-05-02 09:04 UTC
Hello, I'm trying to draw some SVG's and some of them have texts with umlauts. Jupyter can show the generated svg, but not save it to disk.
Here's a MWE:
```
import drawSvg as draw
d = draw.Drawing(50, 50)
d.append(draw.Text("König", 8, 25,25,center=True))
d.saveSvg("test.svg")
```

The error is UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 1: ordinal not in range(128)

Any ideas?

**Comment by cduck** [comment] 2021-05-02 13:23
drawSvg fully supports Unicode and I can run your example with no errors so I'm not sure what is wrong.  Is it possible you are running Python 2, not 3?

To help find the root cause, can you post the result of running each of these in Jupiter cells?
```python
import sys
print(sys.version)
```
```bash
pip show drawsvg
```
```python
with open('test.txt', 'w') as f:
    f.write('ö')
```

**Comment by chrimbo** [comment] 2021-05-02 13:31
Hm. ok Let's see
> 
> To help find the root cause, can you post the result of running each of these in Jupiter cells?
> 
> ```python
> import sys
> print(sys.version)
> ```
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
> ```shell
> pip show drawsvg
> ```
Name: drawSvg
Version: 1.7.0
Summary: A Python 3 library for programmatically generating SVG images (vector drawings) and rendering them or displaying them in a Jupyter notebook
Home-page: https://github.com/cduck/drawSvg
Author: Casey Duckering
Author-email: None
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: numpy, imageio, cairoSVG
Note: you may need to restart the kernel to use updated packages.
> ```python
> with open('test.txt', 'w') as f:
>     f.write('ö')
> ```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-3-51e44fe01ef4> in <module>
      1 with open('test.txt', 'w') as f:
----> 2     f.write('ö')

UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 0: ordinal not in range(128)

**Comment by cduck** [comment] 2021-05-02 13:46
I'm not sure why the last one is failing.  Does http://stackoverflow.com/questions/24717808/ddg#31096757 help?  If you can fix that error, drawSvg should also work.

**Comment by chrimbo** [comment] 2021-05-02 14:01
Hi, I already visited this thread but it didn't help.

Eventually I fixed it. My Jupyter runs on a Ubuntu docker container. There was the locale set to POSIX. After installing de_DE.UTF-8 and setting this as the default locale the test and drawSvg works now.

Thanks

**Comment by cduck** [comment] 2021-05-02 14:34
Great.  Maybe I should add the encoding argument to saveSvg so users can override the system default.

**Comment by 1081** [comment] 2021-08-07 21:27
I have a similar issue with an ascii arrow "➝" on Windows 10, but no problems with macOS.

**Comment by cduck** [comment] 2021-08-07 22:28
OK.  I have a fix for this in https://github.com/cduck/drawSvg/tree/fix-enc.  Can you try it and let me know if it solves your issue?

Run the following to install drawSvg with the fix:
```bash
pip uninstall drawSvg
pip install git+https://github.com/cduck/drawSvg@fix-enc
```

**Closed** 2021-11-02 22:25 UTC

**Comment by cduck** [comment] 2021-11-02 22:42
I believe this is fixed by #65.  Please reopen this issue if you see this error in drawSvg version 1.8.3 or later.

**Comment by chrimbo** [comment] 2021-11-08 19:00
Hi, I just hooked up a new docker container to check. It is solved now, even with locale set to posix. Thanks man. Good job!

**Comment by cduck** [comment] 2021-11-08 23:54
Great.  Thanks for confirming.
