### ISSUE TITLE
save_png and save_svg produce different images

### ISSUE THREAD

**Issue by fajardogomez** [cduck/drawsvg#103] opened 2023-08-02 04:26 UTC
I noticed differences in the outputs from saving the same drawing as either an svg or png file. In png format, the text positions and decorations don't behave as expected. For example, the following code
```python
import drawsvg as dw
d = dw.Drawing(50, 50, origin='center')
r = dw.Rectangle(-20, -15, 40, 30, stroke='black', stroke_width=2)
t = dw.Text('1', x=0, y=0, font_size = 20, text_anchor='middle', dominant_baseline='middle', text_decoration='overline', fill='blue')
d.append(r)
d.append(t)
d.save_svg('test.svg')
d.save_png('test.png')
```
produces this svg graphic:
![test](https://github.com/cduck/drawsvg/assets/109635630/37dabd06-704e-4382-89de-f1bba0f95653)

and a png graphic that has offset the text position and ignores the overline decoration:
![test](https://github.com/cduck/drawsvg/assets/109635630/77467c80-a666-4dd5-9b9d-a8df1dd4ca4c)

I don't know if this is a feature or a bug (maybe some things can't be adapted to png?), but the behavior I expected was that the png image would be no different from what I'd obtain using a png export in Inkscape.

**Comment by cduck** [comment] 2023-08-04 05:01
Thanks for sharing this issue.  The PNG output is generated using the [CairoSVG](https://cairosvg.org/documentation/) library which mostly supports the SVG 1.1 specification but it appears the `text_decoration` is [an SVG 2 feature](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-decoration#specifications).

Ideally the PNG would match your browser's display of the SVG, but unfortunately each rendering engine supports a different subset of the SVG specification.  For now, I would suggest using an alternative tool to convert the SVG to a PNG if you need to use advanced text features.

I'm going to close this as a duplicate of #102.  Please reply there with further comments about rendering differences and rendering backends.

**Closed by cduck** 2023-08-04 05:01 UTC
